name: dlp_learn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - pyyaml
  - tqdm
  - pillow
  - scikit-image
  - matplotlib
  - pydantic
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # 사용하는 CUDA 버전에 맞게 수정하세요 (예: 11.8, 12.1)
  - pip
  - pip:
    - opencv-python
    - hydra-core
    - omegaconf
    - natsort
    - wandb
    - torchmetrics
    - h5py
    - requests
    - sympy