# train.yaml

defaults:
  - _self_
  - model: fivarnet_crop1   # 모델 설정
  - data: local_gpu         # 데이터 경로 설정
  - LRscheduler: ExponentialLR        # ⬅️  추가 - https://gaussian37.github.io/dl-pytorch-lr_scheduler/참고
  - LossFunction: SSIM+L1
  - training: base          # base or vessl_vramMin
  - early_stop: none    # 조기종료 기능 : early_stop or none
  - evaluation: leaderboard_cluster
  - optimizer: nadam          # ⬅️ 새로 추가  
  - aug: mraugment    # ⬅️ 새로 추가 none or mraugment
  - centerCropPadding: crop_kspace # crop_zero or crop_noise or crop_kspace
  - maskDuplicate: acc4_acc8       # acc4_acc8 or none
  - maskAugment: universal             # universal or basic or none 
  - collator: identity          # 또는 dynamicCompress or identity or identity_debug
  - compressor: scc  # ⬅️ 새로 추가       # gcc, scc, none
  - sampler: grouping          # 또는 grouping or identity

# === Data Preprocessing === -  Mask → Crop → Compress → Tensor
use_crop: false                  # spatial crop 사용 여부
crop_size: [384, 384]           # crop 할 (H, W) - 무조건 짝수로 지정
corner_size : 16

# === 공통 학습 하이퍼파라미터 ===
GPU_NUM: 0
batch_size: 4
val_batch_size: 8     # 검증 배치 크기 (추가)
num_epochs: ${max_epochs} 
max_epochs : 30
warmup_epochs : 3
lr: 1e-3
report_interval: 5000
seed: 430
num_workers: 4

exp_name : fivarnet(8,9,8)-crop(450,450)

# these three are *required* by utils/data/load_data.py → create_data_loaders
input_key:  kspace
target_key: image_label
max_key:    max

wandb:
  project: AMP_sweep
  entity: swpants05-seoul-national-university        # W&B 팀/계정
  use_wandb: true           # false 이면 모든 wandb 로그 함수가 noop
  max_vis_per_cat: 5        # epoch 마다 카테고리별 이미지 수 (0 → 안 올림)

  use_visLogging: true
  use_receptiveField: true
